[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
base = "light"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
showErrorDetails = false
toolbarMode = "minimal"
